import duckGIF from '../images/otter.gif'
import isopolyGIF from '../images/Isopoly_01.gif'
import giphyGIF from '../images/giphy.gif'
import twoGIF from '../images/200.gif'
import hugGIF from '../images/hug.gif'